### ISSUE TITLE
email fiter - read flag not working

### ISSUE THREAD

**Issue by alexandergeiler** [ScottPeterJohnson/purelymail-issues#119]
Hi,
I have created 2 different filters.
One filter set the read flag
![Set Flag](https://user-images.githubusercontent.com/4689177/169712391-ffcbb8e1-fd35-4bdf-9f84-f195bf06f1cc.png)
The other add the read flag
![Add Flag](https://user-images.githubusercontent.com/4689177/169712394-c71e294f-a08d-437d-9257-45d3c4af1aad.png)
 
Both settings does not apply.
All mails that gets moved to the folder stay unread.
![inbox](https://user-images.githubusercontent.com/4689177/169712519-eb2e76dd-5ac1-49f4-850d-b204d35b691f.png)

**Comment by rnkn** [comment]
The read flag needs to be added so the second rule is correct. But it looks like these messages are being caught by the first rule and so not evaluated by the second rule, hence still unread.

**Comment by ScottPeterJohnson** [comment]
Hi! Sorry for the long delay on getting back to you on this. This isn't actually a bug with our implementation, but confusing UI on Roundcube (third party webmail UI)'s part. All you need to do is swap the order of the two actions you have; set or add the flags _before_ moving it to the folder.

Basically, the "Set flags" action changes flags on all subsequent "Move message to" and "Keep message" (including the default implicit Keep that applies if nothing else does) actions. I will make a note to bug the Roundcube authors about this on their issue tracker, although it might only eventually be fixed by replacing their Sieve UI entirely.
