### ISSUE TITLE
Filters appear to not be working

### ISSUE THREAD

**Issue by msfjarvis** [ScottPeterJohnson/purelymail-issues#122]
I have a filter setup like this

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/13348378/175254617-5ec6231a-cf13-4bef-b7bf-ceddc0c5865e.png)

</details>

Yet for the past couple weeks emails that should be caught by this continue coming through to my inbox, like this one:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/13348378/175254824-fd130bca-16cd-4504-8b16-4a0338772620.png)

</details>

I've tried fiddling with the filters to see if maybe it was something I was doing wrong but I can't find anything.

**Comment by ScottPeterJohnson** [comment]
Replace "is equal to" with "contains" OR click the gear and change modifier from "none" to "Envelope".

Basically, "To" "is equal to"  translates to an exact header comparison in Sieve, which is not generally what you want to do against a header address. This is because the "To" header can contain stuff like "<>" and quoted user names, so an exact match will often fail.

Let me know if that was your issue!

**Comment by msfjarvis** [comment]
> Replace "is equal to" with "contains" OR click the gear and change modifier from "none" to "Envelope".
> 
> Basically, "To" "is equal to" translates to an exact header comparison in Sieve, which is not generally what you want to do against a header address. This is because the "To" header can contain stuff like "<>" and quoted user names, so an exact match will often fail.
> 

Oh, that actually makes total sense. I'll monitor my inbox for a day or two and close the issue if everything works fine with these changes. Thanks for the quick help!

**Comment by msfjarvis** [comment]
Seems to be working correctly, thanks again!
