### ISSUE TITLE
Add Wise as payment option

### ISSUE THREAD

**Issue by rEnr3n** [ScottPeterJohnson/purelymail-issues#128]
Please add [Wise](https://wise.com/) as an alternative to Paypal.

**Comment by rnkn** [comment]
Hi @rEnr3n can you not use your Wise card/virtual card like any other credit card?

**Comment by ScottPeterJohnson** [comment]
Yea I think I'd prefer if you used the Wise card rather than adding a specific integration. The reason is that payment options are complicated beasts; Stripe/Paypal do security, fraud monitoring, money management, refunds, taxes, etc. I'd prefer to keep them at a minimum because I don't like messing with that stuff.

**Comment by rEnr3n** [comment]
Sorry for the late reply. I'll try the card feature next time.
