### ISSUE TITLE
The signup page thinks that passwords don't match

### ISSUE THREAD

**Issue by nsajko** [ScottPeterJohnson/purelymail-issues#138]
On the signup page, after entering all information and checking all boxes, I click on `Pay (Card)`. At this moment the Web page says that my passwords don't match, even though both password fields were filled by copying a password manager-generated password.

But, this doesn't happen if I manually delete a single character from both password input fields after copying over the password. Or if I manually append some character. So that seems to be a work around.

Example password:
```
Q/avR'=68q{DEQgqnQw[W&8\5#7O@
```

So there are two issues here:
1. The signup page only warns me about this at the last moment. Seems like it would make sense to warn as soon as the user stops typing, or as soon as another input field or check box is modified. But this issue is less important.
2. The passwords do match

**Comment by nsajko** [comment]
After signing up logging in works fine. So the workaround was fine for me.

**Comment by rogerjane-nhs** [comment]
I've noticed that one or two fields will allow the browser to re-format the entry (e.g. upper case the first letter) where it doesn't make sense to do so.  I've seen this where an email address is required for example.  I wonder if it's doing it in a password field where editing the field after a copy/paste is inhibiting this action.

**Comment by ScottPeterJohnson** [comment]
The little bit of JS updating the password matching apparently didn't register "change" on the repeat field, though it did register "keyup". I've added change too so it should work with pasting or password managers.

> The signup page only warns me about this at the last moment. Seems like it would make sense to warn as soon as the user stops typing, or as soon as another input field or check box is modified. But this issue is less important.

It does mark when it's wrong, but the default browser UI for "this field is invalid" turns out not to be so great, and the CSS support for :user-invalid isn't quite there yet. (If I just used :invalid it would immediately make everything red which would be anxiety-inducing).
I've hacked a fix for specifically the repeat field, so it should show a nice red border when wrong after it's been interacted with.

> I've noticed that one or two fields will allow the browser to re-format the entry (e.g. upper case the first letter) where it doesn't make sense to do so. I've seen this where an email address is required for example. I wonder if it's doing it in a password field where editing the field after a copy/paste is inhibiting this action.

Browsers might assume inputs marked "email" are case-insensitive; happily they are for us, although it's actually an _assumption_ that they are in general.
