### ISSUE TITLE
Mail import/export tool does not automatically create subfolders when importing

### ISSUE THREAD

**Issue by natjms** [ScottPeterJohnson/purelymail-issues#176]
I've been using the mail import/export tool to migrate my emails from my old email server over to Purelymail, and some of my mailboxes have complicated trees of subfolders. When starting the import task, I was invited to create new folders for them using the dot notation (i.e. `Archive.2022` for Archive->2022).

Once this was done, I noticed that these folders weren't showing up in the web mail client or Thunderbird. When I created the folder manually, it was immediately populated with all the emails that were supposed to be there.

I'm not particularly familiar with how email servers work internally but it sounds a lot like the emails are getting imported while the folders aren't being created, leaving them orphaned

**Comment by flibustenet** [comment]
Same for me, it looks like import `fold/subfold` doesn't create `fold` and then `subfold` under `fold` but a folder with name `fold/subfold` (wihch offlinemap doesn't like a lot because of the `/` in the name).

**Comment by ScottPeterJohnson** [comment]
I think natjm's problem is because of the IMAP protocol; Basically, the folders are created and exist and what you're seeing is that you're not initially "subscribed" to them. When the import tools "creates" them, it doesn't subscribe.

Anyway, the import tool now autosubscribes to folders it creates. It should also have better handling for folder separators, converting Foo/Bar into Foo.Bar (Purelymail uses . instead of / for some arcane reason; I'd switch it but it'd be work to do it now).

**Comment by flibustenet** [comment]
Thanks it works well now. A little things would be to show the folder by alphabetic order if you like.
