### ISSUE TITLE
Mail storage usage is higher than it actually is

### ISSUE THREAD

**Issue by mjyut** [ScottPeterJohnson/purelymail-issues#238]
When I check the email storage usage for one of my accounts on the [Billing page](https://purelymail.com/manage/billing/), it seems to be higher than it actually is.

---

It will be displayed like this.
(My actual account name will be sent to support via email.)

| User                    | Compressed | Uncompressed |
| ----------------------- | ---------- | ------------ |
| ***@purelymail.com      | 90.2 MiB   | 98.5 MiB     |

However, there are actually no emails currently stored in this account.
Not just now, but for months there has been almost zero email stored in this account.

I remember performing some rather complicated operations in the past, such as changing my account name.
I think I was using email storage at the time, so that may have remained in the calculation for some reason.

There is a possibility of bugs, so I would appreciate it if you could check it. 

(I am completely satisfied with Purelymail's price and service. I don't need a retroactive refund even if there was a mistake in the calculation of my usage.)

**Comment by ScottPeterJohnson** [comment]
There was a longstanding issue where the storage calculation updated wrong with search indexing files. I think that issue is now fixed, but I need to run a DB process to fix the tallies for other existing accounts. I ran it on your account and the compressed usage seems to have gone down to 4.6 MB; that looks like it's for spam learning and is normal.

**Comment by mjyut** [comment]
Thank you for your response. The issue has been completely resolved.
